# Default Configuration
spring:
    profiles:
        active: dev


logging:
    path: /tmp/logs/com.bellotapps.examples/spring-boot-example

custom:
    rolling-policy:
        max-history: 5

---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development

logging:
    config: classpath:logging/logback-spring-dev.xml

---
# Configuration for Staging Environment

spring:
    profiles:
        - staging

logging:
    config: classpath:logging/logback-spring-staging.xml

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production
logging:
    config: classpath:logging/logback-spring-prod.xml